# Alacritty Configuration for MacBook M1 Air (Asahi Linux)
# Optimized for Czech keyboard layout and modern terminal experience

# Import additional config files
# import = [
#   "~/.config/alacritty/themes/catppuccin-mocha.toml"
# ]

# Window configuration
[window]
# Window dimensions (changes require restart)
dimensions = { columns = 100, lines = 30 }

# Window position (changes require restart)
# position = { x = 0, y = 0 }

# Window padding
padding = { x = 10, y = 10 }

# Spread additional padding evenly around the terminal content
dynamic_padding = true

# Window decorations
decorations = "buttonless"

# Opacity
opacity = 0.92

# Startup mode
startup_mode = "Windowed"

# Window title
title = "Alacritty"

# Allow terminal applications to change Alacritty's window title
dynamic_title = true

# Window class (Linux/BSD only)
[window.class]
instance = "Alacritty"
general = "Alacritty"

# GTK theme variant (Linux/BSD only)
gtk_theme_variant = "dark"

# Scrolling configuration
[scrolling]
# Maximum number of lines in the scrollback buffer
history = 10000

# Scrolling distance multiplier
multiplier = 3

# Font configuration
[font]
# Point size
size = 13.0

# Offset is the extra space around each character
offset = { x = 0, y = 1 }

# Glyph offset determines the locations of the glyphs within their cells
glyph_offset = { x = 0, y = 0 }

# Use built-in font for box drawing characters
builtin_box_drawing = true

# Normal (roman) font face
[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

# Bold font face
[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"

# Italic font face
[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

# Bold italic font face
[font.bold_italic]
family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

# Colors (Catppuccin Mocha theme)
[colors]
# Primary colors
[colors.primary]
background = "#1e1e2e"
foreground = "#cdd6f4"
dim_foreground = "#7f849c"
bright_foreground = "#cdd6f4"

# Cursor colors
[colors.cursor]
text = "#1e1e2e"
cursor = "#f5e0dc"

# Vi mode cursor colors
[colors.vi_mode_cursor]
text = "#1e1e2e"
cursor = "#b4befe"

# Search colors
[colors.search]
[colors.search.matches]
foreground = "#1e1e2e"
background = "#a6adc8"

[colors.search.focused_match]
foreground = "#1e1e2e"
background = "#a6e3a1"

# Footer bar colors
[colors.footer_bar]
foreground = "#1e1e2e"
background = "#a6adc8"

# Hints colors
[colors.hints]
[colors.hints.start]
foreground = "#1e1e2e"
background = "#f9e2af"

[colors.hints.end]
foreground = "#1e1e2e"
background = "#a6adc8"

# Selection colors
[colors.selection]
text = "#1e1e2e"
background = "#f5e0dc"

# Normal colors
[colors.normal]
black = "#45475a"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#bac2de"

# Bright colors
[colors.bright]
black = "#585b70"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#a6adc8"

# Dim colors
[colors.dim]
black = "#45475a"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#bac2de"

# Indexed colors
[[colors.indexed_colors]]
index = 16
color = "#fab387"

[[colors.indexed_colors]]
index = 17
color = "#f5e0dc"

# Bell configuration
[bell]
animation = "EaseOutExpo"
duration = 0
color = "#ffffff"

# Background opacity
background_opacity = 0.92

# Selection
[selection]
# This string contains all characters that are used as separators for "semantic words" in Alacritty
semantic_escape_chars = ",│`|:\"' ()[]{}<>\t"

# When set to `true`, selected text will be copied to the primary clipboard
save_to_clipboard = false

# Cursor configuration
[cursor]
# Cursor style
[cursor.style]
shape = "Block"
blinking = "On"

# Vi mode cursor style
vi_mode_style = "None"

# Cursor blinking interval in milliseconds
blink_interval = 750

# If this is `true`, the cursor will be rendered as a hollow box when the window is not focused
unfocused_hollow = true

# Thickness of the cursor relative to the cell width as floating point number from `0.0` to `1.0`
thickness = 0.15

# Terminal configuration
[terminal]
# Controls the OSC 52 behavior for clipboard interactions
osc52 = "CopyPaste"

# Live config reload (changes require restart)
live_config_reload = true

# Shell configuration
[shell]
program = "/usr/bin/fish"
args = ["--login"]

# Working directory
working_directory = "None"

# Send ESC (\x1b) before characters when alt is pressed
alt_send_esc = true

# Offer IPC using `alacritty msg`
ipc_socket = true

# Mouse configuration
[mouse]
# Click settings
double_click = { threshold = 300 }
triple_click = { threshold = 300 }

# If this is `true`, the cursor is temporarily hidden when typing
hide_when_typing = true

# Regex hints
[hints]
# Keys used for the hint labels
alphabet = "jfkdls;ahgurieowpq"

# List with all available hints
[[hints.enabled]]
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^\u0000-\u001f\u007f-\u009f<>\"\\s{-}\\^⟨⟩`]+"
hyperlinks = true
command = "xdg-open"
post_processing = true

[hints.enabled.mouse]
enabled = true
mods = "None"

[hints.enabled.binding]
key = "U"
mods = "Control|Shift"

# Key bindings
[[key_bindings]]
key = "V"
mods = "Control|Shift"
action = "Paste"

[[key_bindings]]
key = "C"
mods = "Control|Shift"
action = "Copy"

[[key_bindings]]
key = "Insert"
mods = "Shift"
action = "PasteSelection"

[[key_bindings]]
key = "Key0"
mods = "Control"
action = "ResetFontSize"

[[key_bindings]]
key = "Equals"
mods = "Control"
action = "IncreaseFontSize"

[[key_bindings]]
key = "Plus"
mods = "Control"
action = "IncreaseFontSize"

[[key_bindings]]
key = "NumpadAdd"
mods = "Control"
action = "IncreaseFontSize"

[[key_bindings]]
key = "Minus"
mods = "Control"
action = "DecreaseFontSize"

[[key_bindings]]
key = "NumpadSubtract"
mods = "Control"
action = "DecreaseFontSize"

# Vi Mode
[[key_bindings]]
key = "Space"
mods = "Shift|Control"
action = "ToggleViMode"

[[key_bindings]]
key = "Space"
mods = "Shift|Control"
mode = "Vi|~Search"
action = "ScrollToBottom"

[[key_bindings]]
key = "Escape"
mode = "Vi|~Search"
action = "ClearSelection"

[[key_bindings]]
key = "I"
mode = "Vi|~Search"
action = "ToggleViMode"

[[key_bindings]]
key = "I"
mode = "Vi|~Search"
action = "ScrollToBottom"

[[key_bindings]]
key = "C"
mods = "Control"
mode = "Vi|~Search"
action = "ToggleViMode"

[[key_bindings]]
key = "Y"
mods = "Control"
mode = "Vi|~Search"
action = "ScrollLineUp"

[[key_bindings]]
key = "E"
mods = "Control"
mode = "Vi|~Search"
action = "ScrollLineDown"

[[key_bindings]]
key = "G"
mode = "Vi|~Search"
action = "ScrollToTop"

[[key_bindings]]
key = "G"
mods = "Shift"
mode = "Vi|~Search"
action = "ScrollToBottom"

[[key_bindings]]
key = "B"
mods = "Control"
mode = "Vi|~Search"
action = "ScrollPageUp"

[[key_bindings]]
key = "F"
mods = "Control"
mode = "Vi|~Search"
action = "ScrollPageDown"

[[key_bindings]]
key = "U"
mods = "Control"
mode = "Vi|~Search"
action = "ScrollHalfPageUp"

[[key_bindings]]
key = "D"
mods = "Control"
mode = "Vi|~Search"
action = "ScrollHalfPageDown"

[[key_bindings]]
key = "Y"
mode = "Vi|~Search"
action = "Copy"

[[key_bindings]]
key = "Y"
mode = "Vi|~Search"
action = "ClearSelection"

[[key_bindings]]
key = "Copy"
mode = "Vi|~Search"
action = "ClearSelection"

[[key_bindings]]
key = "V"
mode = "Vi|~Search"
action = "ToggleNormalSelection"

[[key_bindings]]
key = "V"
mods = "Shift"
mode = "Vi|~Search"
action = "ToggleLineSelection"

[[key_bindings]]
key = "V"
mods = "Control"
mode = "Vi|~Search"
action = "ToggleBlockSelection"

[[key_bindings]]
key = "V"
mods = "Alt"
mode = "Vi|~Search"
action = "ToggleSemanticSelection"

[[key_bindings]]
key = "Return"
mode = "Vi|~Search"
action = "Open"

[[key_bindings]]
key = "K"
mode = "Vi|~Search"
action = "Up"

[[key_bindings]]
key = "J"
mode = "Vi|~Search"
action = "Down"

[[key_bindings]]
key = "H"
mode = "Vi|~Search"
action = "Left"

[[key_bindings]]
key = "L"
mode = "Vi|~Search"
action = "Right"

[[key_bindings]]
key = "Up"
mode = "Vi|~Search"
action = "Up"

[[key_bindings]]
key = "Down"
mode = "Vi|~Search"
action = "Down"

[[key_bindings]]
key = "Left"
mode = "Vi|~Search"
action = "Left"

[[key_bindings]]
key = "Right"
mode = "Vi|~Search"
action = "Right"

[[key_bindings]]
key = "Key0"
mode = "Vi|~Search"
action = "First"

[[key_bindings]]
key = "Key4"
mods = "Shift"
mode = "Vi|~Search"
action = "Last"

[[key_bindings]]
key = "Key6"
mods = "Shift"
mode = "Vi|~Search"
action = "FirstOccupied"

[[key_bindings]]
key = "H"
mods = "Shift"
mode = "Vi|~Search"
action = "High"

[[key_bindings]]
key = "M"
mods = "Shift"
mode = "Vi|~Search"
action = "Middle"

[[key_bindings]]
key = "L"
mods = "Shift"
mode = "Vi|~Search"
action = "Low"

[[key_bindings]]
key = "B"
mode = "Vi|~Search"
action = "SemanticLeft"

[[key_bindings]]
key = "W"
mode = "Vi|~Search"
action = "SemanticRight"

[[key_bindings]]
key = "E"
mode = "Vi|~Search"
action = "SemanticRightEnd"

[[key_bindings]]
key = "B"
mods = "Shift"
mode = "Vi|~Search"
action = "WordLeft"

[[key_bindings]]
key = "W"
mods = "Shift"
mode = "Vi|~Search"
action = "WordRight"

[[key_bindings]]
key = "E"
mods = "Shift"
mode = "Vi|~Search"
action = "WordRightEnd"

[[key_bindings]]
key = "Key5"
mods = "Shift"
mode = "Vi|~Search"
action = "Bracket"

[[key_bindings]]
key = "Slash"
mode = "Vi|~Search"
action = "SearchForward"

[[key_bindings]]
key = "Slash"
mods = "Shift"
mode = "Vi|~Search"
action = "SearchBackward"

[[key_bindings]]
key = "N"
mode = "Vi|~Search"
action = "SearchNext"

[[key_bindings]]
key = "N"
mods = "Shift"
mode = "Vi|~Search"
action = "SearchPrevious"

# Search Mode
[[key_bindings]]
key = "Return"
mode = "Search|Vi"
action = "SearchConfirm"

[[key_bindings]]
key = "Escape"
mode = "Search"
action = "SearchCancel"

[[key_bindings]]
key = "C"
mods = "Control"
mode = "Search"
action = "SearchCancel"

[[key_bindings]]
key = "U"
mods = "Control"
mode = "Search"
action = "SearchClear"

[[key_bindings]]
key = "W"
mods = "Control"
mode = "Search"
action = "SearchDeleteWord"

[[key_bindings]]
key = "P"
mods = "Control"
mode = "Search"
action = "SearchHistoryPrevious"

[[key_bindings]]
key = "N"
mods = "Control"
mode = "Search"
action = "SearchHistoryNext"

[[key_bindings]]
key = "Up"
mode = "Search"
action = "SearchHistoryPrevious"

[[key_bindings]]
key = "Down"
mode = "Search"
action = "SearchHistoryNext"

[[key_bindings]]
key = "Return"
mode = "Search|~Vi"
action = "SearchFocusNext"

[[key_bindings]]
key = "Return"
mods = "Shift"
mode = "Search|~Vi"
action = "SearchFocusPrevious"

# (Windows, Linux, and BSD only)
[[key_bindings]]
key = "F"
mods = "Control|Shift"
action = "SearchForward"

[[key_bindings]]
key = "B"
mods = "Control|Shift"
action = "SearchBackward"

# Czech keyboard specific bindings
[[key_bindings]]
key = "Semicolon"
mods = "Alt"
chars = "ů"

[[key_bindings]]
key = "Semicolon"
mods = "Alt|Shift"
chars = "Ů"

[[key_bindings]]
key = "Y"
mods = "Alt"
chars = "ž"

[[key_bindings]]
key = "Y"
mods = "Alt|Shift"
chars = "Ž"

[[key_bindings]]
key = "X"
mods = "Alt"
chars = "č"

[[key_bindings]]
key = "X"
mods = "Alt|Shift"
chars = "Č"

[[key_bindings]]
key = "C"
mods = "Alt"
chars = "ć"

[[key_bindings]]
key = "C"
mods = "Alt|Shift"
chars = "Ć"

[[key_bindings]]
key = "V"
mods = "Alt"
chars = "š"

[[key_bindings]]
key = "V"
mods = "Alt|Shift"
chars = "Š"

[[key_bindings]]
key = "B"
mods = "Alt"
chars = "ř"

[[key_bindings]]
key = "B"
mods = "Alt|Shift"
chars = "Ř"

[[key_bindings]]
key = "N"
mods = "Alt"
chars = "ň"

[[key_bindings]]
key = "N"
mods = "Alt|Shift"
chars = "Ň"

[[key_bindings]]
key = "M"
mods = "Alt"
chars = "ď"

[[key_bindings]]
key = "M"
mods = "Alt|Shift"
chars = "Ď"

[[key_bindings]]
key = "Comma"
mods = "Alt"
chars = "ť"

[[key_bindings]]
key = "Comma"
mods = "Alt|Shift"
chars = "Ť"

# Debug configuration
[debug]
# Display the time it takes to redraw each frame
render_timer = false

# Keep the log file after quitting Alacritty
persistent_logging = false

# Log level
log_level = "Warn"

# Print all received window events
print_events = false 